package utilities.states;

public enum GameState {
    TITLE, PLAY, PAUSE, BATTLE, ENEMY_ENCOUNTER,
    INVENTORY, GAME_OVER, FIRST_LOAD, VICTORY_ENDING,
    LEADERBOARD, LEADERBOARD_MENU, NAME_ENTRY
}
